apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: private-key
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: private-key
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      data:
        private-key.pem: '{{ .key | b64dec | toString }}'
  data:
  - secretKey: key
    remoteRef:
      key: test-cluster
      property: quay-ci-app/private-key\.pem
