apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-quay-ci-app.yaml
- externalsecret-private-key.yaml
- route-api.yaml
- service-api.yaml
configMapGenerator:
- files:
  - config.yaml
  name: config
images:
- digest: sha256:5f6683e71c252ccbdd81132a8fad66244a9a266892d9bf68e1dd6e495d542ba0
  name: quay.io/projectquay/quay-ci-app
