name: Build and Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Publish container image
    env:
      REPOSITORY: quay.io/projectquay/quay-ci-app
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REPOSITORY }}

      - name: Update kustomization.yaml in manifests
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: 4.5.4
          command: |
            version=$(git describe --always)
            git checkout manifests
            kustomize edit set image "${{ env.REPOSITORY }}@${{ steps.docker_build.outputs.digest }}"
            git config --global user.email "quay@users.noreply.github.com"
            git config --global user.name "GitHub Action"
            git commit -a -m "Deploy quay-ci-app $version"
            git push
